# DWA Planner params for MEGAROVER
# Reference: http://wiki.ros.org/dwa_local_planner

DWAPlannerROS:
  acc_lim_x: 0.5 #2.5
  acc_lim_y: 0.0 
  acc_lim_th: 0.3 #3.2
  max_trans_vel: 0.3 #0.55
  min_trans_vel: 0.1 #0.1
  max_vel_x: 0.3 #0.55
  min_vel_x: -0.1 #0
  max_vel_y: 0.0 
  min_vel_y: 0.0
  max_vel_theta: 0.3 #1
  min_vel_theta: 0 #-0.5 #0.4
  yaw_goal_tolerance: 0.3 #0.05
  xy_goal_tolerance: 0.2 #0.1
  latch_xy_goal_tolerance: false #false
  sim_time: 2.0 #1.7
  sim_granularity: 0.025 #0.025
  vx_samples: 10 #3
  vtheta_samples: 20 #20

#  path_distance_bias: 32.0 #default 32
#  goal_distance_bias: 24.0 #default 24
#  occdist_scale: 0.01 #default 0.01
#  forward_point_distance: 0.325 #default 0.325
#  stop_time_buffer: 0.2 #default 0.2
#  scaling_speed: 0.25 #default 0.25
#  max_scaling_factor: 0.2 #default 0.2
#  publish_cost_grid: true #default false
  oscillation_reset_dist: 0.5 #default 0.05
