# golobal costmap params for MEGAROVER

global_costmap:
  # 各TFフレーム名の設定
  global_frame: map
  robot_base_frame: base_link
  
  # 更新頻度
  update_frequency: 2.0 #default 5

  static_map: true #default true

  # タイムスタンプの差の許容量
  transform_tolerance: 0.5 #default 0.2


