# local costmap params for MEGAROVER

local_costmap:
  # 各TFフレームの設定
  global_frame: map #map
  robot_base_frame: base_link

  # 更新頻度の設定
  update_frequency: 3.0 #default 5
  publish_frequency: 3.0 #default 0

  static_map: false #default -
  rolling_window: true #default false

  # ローカルコストマップの計算範囲
  width: 10.0 #default 10
  height: 10.0 #default 10

  # ローカルコストマップの解像度
  resolution: 0.05 #default 0.05

  # タイムスタンプのずれの許容量
  transform_tolerance: 1.0 #default 0.2

