#costmap common params for MEGAROVER

# これ以下の距離にある物体を障害物として扱う
obstacle_range: 3.5
# これ以下の距離に物体が検出された場合、ロボットとその物体との間に障害物はないものとして扱う
raytrace_range: 5.0

# ロボットの大きさに関するパラメータ
# inflation_radius: 0.6
footprint: [[0.65, -0.35], [0.65, 0.35], [-0.65, 0.35], [-0.65, -0.35]]
inflation_radius: 0.3

# コストマップのタイプの設定
map_type: costmap_2d

# LRFの設定 （シミュレータ用）
observation_sources: scan 
scan: {sensor_frame: lrf_link, data_type: LaserScan, topic: scan, marking: true, clearing: true}

